### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [arithy/packcc#1]
Would you like to [add more error handling](https://github.com/arithy/packcc/blob/1012eb3453c22659a27da8ec08d7fcade7a63a43/src/packcc.c#L2624 "Update candidate: generate()") for return values from functions like “[fputs](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fputs.html "Put a string on a stream.")” and “fprintf”?

**Comment by arithy** [comment]
Thank you for your comment.
I introduced error handling wrapper functions also for fputs(), fprintf(), etc.
Please check out the branch 'develop'.

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/arithy/packcc/commit/e78c157ec230bdd63c50bcd3d845e3c54f096c20#diff-263210d6acbeb3578e53a8ca8d003273R294 "Add an error handling feature to every input and output functions").

-----

:crystal_ball:
* Can a function like “[perror](https://pubs.opengroup.org/onlinepubs/9699919799/functions/perror.html "Write error messages to standard error channel.")” be helpful for your error reporting?
* Can it make sense to [move the deletion of files](https://github.com/arithy/packcc/commit/e78c157ec230bdd63c50bcd3d845e3c54f096c20#diff-263210d6acbeb3578e53a8ca8d003273L891 "Update candidate") into [an atexit() callback function](https://pubs.opengroup.org/onlinepubs/9699919799/functions/perror.html "Register a function to run at process termination.")?

-----

* Are you interested to apply [aspect-oriented software development](https://aspectc.org/ "Software development with AspectC++?")?
* Would you like to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in this software?

**Comment by arithy** [comment]
> - Can a function like “perror” be helpful for your error reporting?

Partially yes, because it can print an errno message, but partially no, because it does not provide a formatting functionality like printf().
It needs some efforts to implement an error reporting function with an errno message printing feature, with a formatting functionality, and with portability.
Currently, I don't think errno message is so important for practical use.
So, I want to skip the efforts.

> - Can it make sense to move the deletion of files into an atexit() callback function?

I don't think atexit() is suitable for this case because file deletion is not required in normal situations.
I think it should be explicitly cared whenever context destruction.
Moreover, I dislike callbacks without custom arguments because it needs information passing via global variables.

> - Are you interested to apply aspect-oriented software development?
> - Would you like to encapsulate error detection and corresponding exception handling as a reusable aspect in this software?

In the context of packcc, sorry, I'm not interested.
I want to keep packcc compilable using a standard C compiler.

**Comment by elfring** [comment]
>I think it should be explicitly cared whenever context destruction.

Would you like to improve exception handling another bit also for your software?

**Comment by arithy** [comment]
Yes in general, but no as for packcc.
I want to keep packcc as plain as possible.
I think complete exception handling mechanism in C brings unwanted complexity like longjump().
Such a mechanism is too much, considering that exceptional situations in packcc are very simple.

**Comment by elfring** [comment]
Does the mentioning of exception handling “distract” to much from further software development possibilities to complete the error handling finally?

**Comment by arithy** [comment]
I think error handling is quite important to software for practical use.
So, developers should make efforts to care exceptional cases.
However, in my opinion, the specifications of error handling may be as minimal as required to actual exceptional situations.
Since I want to keep PackCC as simple as possible, I don't adopt luxurious error handling which brings implementation complexity.

**Comment by arithy** [comment]
Anyway, can I close this issue?
I committed the requested feature to the branch `master`.

**Comment by elfring** [comment]
* How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?
* Can it become nicer to specify [the error handling wrappers](https://github.com/arithy/packcc/commit/9f937c1713f2d837b30907dd4bc514b5e4428aef "Add an error handling feature to every input and output functions") as aspects?

**Comment by arithy** [comment]
As I mentioned before, I'm not interested in aspect-oriented framework.

It might be an endless discussion, which seems not to be suitable on this issue board.
I want to quit answering to your questionnaire, OK?

**Comment by arithy** [comment]
As of the [version 1.2.2](https://github.com/arithy/packcc/releases/tag/v1.2.2), error handling features were added to all input and output functions.
I close this issue.
