### ISSUE TITLE
stop parser on error

### ISSUE THREAD

**Issue by aep** [arithy/packcc#24]
i'm trying to implement errors like this:

```
expression
     <- <term> _ { printf("expression: >%s< \n", $1); }
     / <(!EOL .)*> .* { printf("line %d: error: expected expression: %s\n", ((State*)auxil)->line, $0); }
```

but of course ocassionally the .* doesn't consume the entire input to the end, so you get multiple errors for the same line.
is there a way to just stop the parser immediatly?

**Comment by dolik-rce** [comment]
Hi @aep,

That sounds odd. The `.*` should always match everything until the end of file. Can you please post a minimal grammar that exhibits your problem? Preferably with the problematic input.

I think (but I'm not 100% sure) that the parser can only be "peacefully" stopped (i.e. not terminating entire program) at the end of the default rule.

**Comment by aep** [comment]
didnt have much luck getting any error recovery working at all. Might be a lack of understand of PEG in general.
a bigger example with a real language would be really helpful.

.* as a catchall doesnt appear to be the correct thing to do. 
sometimes it hangs, segfaults, runs none of them or all of them.

here's a simple example that does not match

```
tld
    <- const ';' _

const
    <- "const" _ expression _
    /  "const" _ anything { emit_error(auxil, "expected expression", $1s); }

anything
   <- .*


expression
    <- [0-9]+


_   <-  ( [ \t] / EOL )*
EOL <-  ("\r\n"  / "\n" / "\r" ) {}
```

input:
```
const ;
```


debug output indicates it matches fine, but the action isnt run,
likely because the file rule expects the ';' which has already been consumed

```
cc -g main.c -o main
./main example.zz
Evaluating rule file @0 []
  Evaluating rule const @0 []
    Evaluating rule _ @5 []
      Evaluating rule EOL @6 [
]
      Matched rule EOL @6 [
]
      Evaluating rule EOL @7 []
      Abandoning rule EOL @7 []
    Matched rule _ @5 [
]
    Evaluating rule expression @7 []
    Abandoning rule expression @7 []
    Evaluating rule anything @5 [
]
    Matched rule anything @5 [
]
  Matched rule const @0 [const
]
Abandoning rule file @0 [const
]
Syntax error
make: *** [Makefile:2: ALL] Error 1
```

**Comment by aep** [comment]
what i'm trying to do is give the user helpful error messages by assuming that "const"  HAS TO be followed by an expression. if it wasnt followed by an expression, that is unambiguously an error and we can just stop trying.

But i'm not sure if PEG can even express that, because it really just tries to match the default rule somehow, giving you a helpful "it didnt match".

**Comment by aep** [comment]
using a lookahead ! instead of a .* makes it execute, but it segfaults later when contuing the rest of the file. 
hence my question if its possible to stop the parser

```

file
    <- tld+


EOS <- ';'

tld
    <- const
    /  _
    /  <(!EOL .)+> { emit_error(auxil, "expected top level declaration", $1s); }


const
    <- "const" _ "ident"_ "=" _ expression _ EOS
    /  "const" _ <!"ident">                   { emit_error(auxil, "expected ident ", $1s); }


expression
    <- [0-9]+


_   <-  ( [ \t] / EOL )*
EOL <-  ("\r\n"  / "\n" / "\r" ) 
```

**Comment by aep** [comment]
since we're at it, this one hangs:

```
file
    <- tld
    / _

tld
    <- const ';'


const
    <- "const" _ ident _ "=" _ expression _
    /  "const" _ <(!ident)> _   { emit_error(auxil, "expected ident ", $1s); }

ident
    <- "ident"


expression
    <- [0-9]+


_   <-  ( [ \t] / EOL )*
EOL <-  ("\r\n"  / "\n" / "\r" ) 
```

**Comment by aep** [comment]
i also have an example of if triggering twice, but its too long. either way, we need a way to abort the parser.
setting a flag so the next call to PCC_GETCHAR returns EOF didnt help, it appears to have a large lookahead buffer

**Comment by dolik-rce** [comment]
Thanks for elaborating on what you're trying to do. Let's start with the first example.

You have to be careful, when using `*`, it is very greedy and it often eats more than you want. There was only two small problems in the example you posted, that prevented it from working correctly:
 1. You had `*` in `_` rule, so all whitespaces would be optional (e.g. `const42` would be valid), I guess that was not really you intention
 2. More importantly, the rule `anything` greedily ate your semicolon, therefore `tld` could never be matched, since it requires to have `';'` after the `const`.
 
 Here is a full working grammar:
 ```
 tld
    <- const ';' _

const
    <- "const" _ expression _*
    /  "const" _ anything { printf("expected expression: %s\n", $0); }

anything
   <- (!(EOL / ';') .)*

expression
    <- [0-9]+

_   <-  ( [ \t] / EOL )+
EOL <-  ("\r\n"  / "\n" / "\r" )
```

Note that you can also use "error actions", denoted `~{ ... }`, to immediately report where the parsing failed. In the example above, you'd just could replace const rule with this:
```
const
    <- "const" _ expression ~ { printf("expected expression: %s\n", $0); } _*
```
The code will be executed immediately when the expression fails to be matched.

**Comment by dolik-rce** [comment]
> since we're at it, this one hangs

Infinite execution is most often result of having repeated empty match at the end of the input. In your example it is probably caused by the `_` in `file`. It always matches zero characters, therefore it consume the same place in the buffer over and over and never finishes.

**Comment by dolik-rce** [comment]
I agree that having the ability to stop the parser at the place of error would be a nice feature. I'm just not sure that it is a "low hanging fruit" :slightly_smiling_face:

It might be actually easier to write a better documentation. Perhaps some FAQ, that would point out most common problems and their solutions. I remember hitting some of the same troubles as you not so long ago...

**Comment by dolik-rce** [comment]
> a bigger example with a real language would be really helpful.

I can only point you to the parsers in universal-ctags:
 - [varlink.peg](https://github.com/universal-ctags/ctags/blob/master/peg/varlink.peg) - simple interface description format 
 - [kotlin.peg](https://github.com/universal-ctags/ctags/blob/master/peg/kotlin.peg) - quite komplex grammar describing [Kotlin language](https://kotlinlang.org/)
 
 Unfortunately, neither of them tries to report errors to users (because ctags assumes input is always correct).

**Comment by masatake** [comment]
About broken input, I would like you to see the change I made in universal-ctags/packcc.
https://github.com/universal-ctags/packcc/commit/37c1b8863550001441e0e7eb40c69c2ea6aae0fe

**Comment by dolik-rce** [comment]
> using a lookahead ! instead of a .* makes it execute, but it segfaults later when contuing the rest of the file.

This one looks like a bug. I have narrowed it down a bit and posted as a separate issue #28.

**Comment by dolik-rce** [comment]
@masatake: Yes, that looks like the same error that @aep encountered. See #24. Your fix looks more like a workaround, I'm wondering when exactly does it happen that the context becomes corrupted.... I'll try to look into it if I get some spare time over the weekend.

**Comment by masatake** [comment]
> I'll try to look into it if I get some spare time over the weekend.

Yes, please!  I opened  #25 that enumerates some interesting changes. I would like you to see them, too.

**Comment by aep** [comment]
here's a full  example of where i'd really appreciate early abort

[main.peg.txt](https://github.com/arithy/packcc/files/6250994/main.peg.txt)

input:

```
const i = a.a * b . 3 *;
```


results in TWO errors, one for each nested rule


```
syntax error in example.zz:1:22
 | const i = a.a * b . 3 *;
 |                       ^
 | expected ;

syntax error in example.zz:1:22
 | const i = a.a * b . 3 *;
 |                       ^^^
 | expected top level declaration
```

**Comment by dolik-rce** [comment]
Nice grammar. 

The two errors are actually correct behaviour, because it sees the input line as two separate `tld`s: First it parses `const i = a.a * b . 3 `, where the semicolon is missing, then it sees the rest of the line `*;`, which is obviously not a valid top level declaration.

I'd suggest few minor changes:

Move the semicolon checking into `tld`. You'll have less duplicated code and less problems with duplicated errors. Something like this works well:
```
tld
    <-  statement
    /   __
    /   <.+> {emit_error(auxil, "expected top level declaration", $0s, $0e); }

statement
    <- (const / static / fn) _ ";"
    /  (const / static / fn) _ <[^;]*> ";" { emit_error(auxil, "expected ;", $1s, $1e); }
```

Static and const assignment could probably also be refactored in similar way. 

Arglist could be little simpler to parse without recursion:
```
arglist
    <- arg (_ ',' _ arg) *
    /   _
```
The generated parser will be easier to debug and slightly faster. And if you make it optional by using `arglist?` in `fn`, you won't even need the whitespace only case.

It is rather hard to come with unambiguous, simple grammar for a language in PEG, since there are so many possibilities and some constructs can be written in multiple ways. On the other hand, PEG is very versatile, so you can implement anything you can think of :slightly_smiling_face:

**Comment by arithy** [comment]
@aep, I recommend you to use the rules shown below.
~~~~
ident
   <- !keyword L(L/D)*

keyword
   <- kw_const
    / kw_static

kw_const  <- 'const'  !(L/D)
kw_static <- 'static' !(L/D)

D <- [0-9_]
L <- [a-zA-Z_]
~~~~
Your grammar allows `consti =` as well as `const i =`.
This problem can be resolved by appending `!(L/D)` after a keyword string.

**Comment by arithy** [comment]
This issue can be solved using `setjmp()` and `longjmp()`.
I'll show an example of modifications below.

```C
+   #include <setjmp.h>

    typedef struct {
        const char *  filename;

        ....

        int     abort;

+       jmp_buf jmp;
    } State;
```

```C
    static void emit_error(State *self , const char *reason, int start, int end) {
        self->abort = 1;

        ....

        fprintf(stderr, " | %s\n", reason);

+       longjmp(self->jmp, 1);
    }
```

```C
    zz_context_t *ctx = zz_create(&s);
+   if (setjmp(s.jmp) == 0) {
        while (zz_parse(ctx, NULL));
+   }
+   else {
+       // some recovery process
+   }
    zz_destroy(ctx);
```

I didn't integrate the quick stopping feature intentionally because I bore the following fact in mind.
Many compilers usually report multiple errors so that users can find multiple mistakes at one compile time.
The compilers end after the number of reported errors reaches a certain limit.
This behavior can also be simply realized by using `setjmp()` and `longjmp()`.

**Comment by arithy** [comment]
Let me add a comment regarding https://github.com/arithy/packcc/issues/24#issuecomment-812857359 in case.
All strings `"const"` and `"static"` in your grammar should be replaced with `kw_const` and `kw_static` respectively.
In addtion, `"fn"` should be replaced with a rule `kw_fn <- 'fn' !(L/D)` as well.

**Comment by arithy** [comment]
@aep, can I close this issue with the answer https://github.com/arithy/packcc/issues/24#issuecomment-812862521 ?

**Comment by aep** [comment]
sorry, yes. thank you for your help, it's been good input

I wanted to respond with the completed grammar, but couldnt get it done yet.

   https://github.com/zetzit/zz/blob/selfhosting/parser/main.peg
