### ISSUE TITLE
Changes made in Universal Ctags project

### ISSUE THREAD

**Issue by masatake** [arithy/packcc#25]
I should make pull requests. However, I cannot find time for doing it now.
So, allow me just listing some of them here:

- [x] enhancement [Introduce -i option for putting an #include directive earlier](https://github.com/universal-ctags/packcc/commit/e2f1182878ca2df8ad9a6d5ef642fd3a8a715f7a)
- [x] fix [ Never parse within a same context once got a syntax error ](https://github.com/universal-ctags/packcc/commit/37c1b8863550001441e0e7eb40c69c2ea6aae0fe)
- [x] enhancement? [Provide the way to use strnlen of system implementation when compiling generated code](https://github.com/universal-ctags/packcc/commit/b40dbf08a58f42530242d54367a96a74914e2c3b)
- [x]  fix? [Use PRIuPTR instead of SIZE_T_FMT_CHAR](https://github.com/universal-ctags/packcc/commit/42c941764dd8aeafc7390976cdefbdfe75cef951)
- [x] enhancement? [Provide the way to force compiling strnlen of system implementation](https://github.com/universal-ctags/packcc/commit/d4f7a2355be31bcdb45618b12fdfebc894ac2c85)
- [x] enhancement? [Provide the way to replace printf formatter for size_t ](https://github.com/universal-ctags/packcc/commit/b728b1ec671cf83d070acf7014c20c1609a8a03d)

If possible, could you cherry-pick some of them?
If you know the same change is already introduced, let me know. I will remove the associated item from the list.

**Comment by dolik-rce** [comment]
￼> fix Never parse within a same context once got a syntax error

This might be fixed by #29. I'll try to run some tests later, after (and if) that PR is merged.

>￼ enhancement? Provide the way to use strnlen of system implementation when compiling generated code
￼> enhancement? Provide the way to force compiling strnlen of system implementation

Cherry picked in #30.

￼> enhancement? Provide the way to replace printf formatter for size_t
> fix? Use PRIuPTR instead of SIZE_T_FMT_CHAR

These should not be needed. It seems that all `size_t` values are cast to unsigned long and printed via `%lu`.

> enhancement Introduce -i option for putting an #include directive earlier

This one is a big change. I don't really like the idea of adding it as a command line option. @masatake: I know you first tried to add it as a directive `%earlysource { ... }`, but you've found that it would not be simple and used option instead. However, I think it is quite possible to decouple the parsing from code generation and do this the proper way. @masatake  would you mind if I tried it that way? It would actually be more versatile, since currently it is only possible to add single include, but with `%earlysource` it would be possible to add any number of code blocks, not only includes. And it would also be possible to easily add similar directives `%earlyheader` and `%earlycommon`, to keep things consistent...

**Comment by arithy** [comment]
@masatake, if @dolik-rce's understanding told in https://github.com/arithy/packcc/issues/24#issuecomment-812480919 is right, the second issue 'fix Never parse within a same context once got a syntax error' should have been solved by 298b1f746e9dac1f2e2c659e777eb2ed68d8d471 (based on a hint gotten from #29).
Can I check its checkbox?

**Comment by arithy** [comment]
@masatake, as for the 4th and 6th issues 'fix? Use PRIuPTR instead of SIZE_T_FMT_CHAR' and 'enhancement? Provide the way to replace printf formatter for size_t', could you manage them in Universal Ctags side?
If it's difficult or not elegant, please let me know its background.

**Comment by arithy** [comment]
The 1st issue 'enhancement Introduce -i option for putting an #include directive earlier' has been solved by the PR #31 that introduces %earlyheader, %earlysource, and %earlycommon directives instead of the option -i.

**Comment by k-takata** [comment]
> as for the 4th and 6th issues 'fix? Use PRIuPTR instead of SIZE_T_FMT_CHAR' and 'enhancement? Provide the way to replace printf formatter for size_t', could you manage them in Universal Ctags side?
> If it's difficult or not elegant, please let me know its background.

MSVC 2013 doesn't support %z formatter, and unsigned long is 32 bits even on 64-bit Windows. So, PRIuPTR is needed.

**Comment by arithy** [comment]
@k-takata, I understand.

> unsigned long is 32 bits even on 64-bit Windows.

I didn't notice this. Thanks for the information.

**Comment by arithy** [comment]
I believe the background problem from which the following issues came up is solved by the commit fda7180eb9d1e75f4533818da199079f1a425915.
- fix? Use PRIuPTR instead of SIZE_T_FMT_CHAR
- enhancement? Provide the way to replace printf formatter for size_t

@masatake, is my understanding right?

**Comment by k-takata** [comment]
https://github.com/arithy/packcc/blob/fda7180eb9d1e75f4533818da199079f1a425915/src/packcc.c#L82

`#ifdef _WIN64` should be better.
MinGW-w64 also uses the LLP64 data model. There's also an ARM64 version of Windows.

**Comment by arithy** [comment]
@k-takata, thanks.

**Comment by dolik-rce** [comment]
It seems that ctags works fine with current version of PackCC, aside from little issue with constness in PCC_FREE, that only manifests itself on 64bit windows and MSVC compiler, but that should be easy to fix.

I believe this issue can be closed now, do you agree @masatake?

**Comment by masatake** [comment]
I'm sorry to be late. Please, close this. To confirm the result of changes made these days, I have to switch the version of packcc used in u-ctags from https://github.com/universal-ctags/packcc to arithy/packcc. It will take time. 
@dolik-rce, @arithy, and @k-takata, thank you for taking the time for this issue.
I'm very surprised at things going so fast and quick.
