### ISSUE TITLE
C predicates

### ISSUE THREAD

**Issue by andrewchambers** [arithy/packcc#45]
Would it be possible to allow C predicates to participate in matching? 

For example:

```
foonumber <- <[0-9]+> ?? { atoi($1) > 50 }
```

**Comment by arithy** [comment]
It's an interesting functionality.
However, I don't plan to realize it due to the reasons below:
- PackCC is designed to see just __syntax__, not __semantics__.
  That is, PackCC recognizes all inputs as a structure of strings, and doesn't care their meanings (like numeric values).
- The semantics should be cared in the next phase after PackCC's processing.
- I hope PackCC is kept as simple as possible.

**Comment by andrewchambers** [comment]
No problem, thanks for explaining.
